created a django rest api which return information of trips
Muazam-Husnain/django-training pull request #3
Opened 2020-10-15 10:50 UTC by Muazam-Husnain

Created a django rest api which returns information of all trip on url 'api/v1/trips'
<img width="1680" alt="Screenshot 2020-10-15 at 3 48 31 PM" src="https://user-images.githubusercontent.com/55695791/96113685-f54e5b80-0efd-11eb-8869-5ad1a016e752.png">

2020-10-26 07:54 UTC, awaisdar001 commented on learn_django/trip_project/serializers.py
> +    host = serializers.StringRelatedField()
Why `StringRelatedField` is needed for `host`?

2020-10-26 07:55 UTC, awaisdar001 requested changes
Have separate serializers for host and destination_location.

2020-10-27 07:39 UTC, Muazam-Husnain commented
![Uploading Screenshot 2020-10-27 at 12.39.10 PM.png…]()

2020-10-27 07:45 UTC, Muazam-Husnain commented
![Uploading Screenshot 2020-10-27 at 12.39.10 PM.png…]()

2020-10-27 07:46 UTC, Muazam-Husnain commented
<img width="1680" alt="Screenshot 2020-10-27 at 12 39 10 PM" src="https://user-images.githubusercontent.com/55695791/97271376-4c372780-1852-11eb-913c-ee720fd07f90.png">

2020-10-27 08:32 UTC, awaisdar001 requested changes
I need data as 
```
...
"host": {"name": "Travel guide of Pakistan", "number" : 123},
"destination_location": {"name": "Lahore"},
"start_location": {"name": "Lahore"},
```


2. I would not expose `id` field in the API. 

3. I would like to add 10 trips and then share a screenshot.

2020-10-27 09:19 UTC, Muazam-Husnain commented
<img width="1680" alt="Screenshot 2020-10-27 at 2 15 10 PM" src="https://user-images.githubusercontent.com/55695791/97281434-54499400-185f-11eb-876d-c833dc560d9f.png">
<img width="1680" alt="Screenshot 2020-10-27 at 2 15 06 PM" src="https://user-images.githubusercontent.com/55695791/97281442-590e4800-185f-11eb-95be-570c95d80fb5.png">

2020-10-29 07:35 UTC, awaisdar001 approved these changes
This looks good. 

* You need to know how to rename field names in APIs without changing the database table attributes. 
* Do not expose `id` anywhere in the models. the right solution here was to use `exclude` rather than manually typing in all the field names in `include`. 


have those changes and you can merge this PR.

2020-10-29 07:59 UTC, merged